// food_data.dart

final List<Map<String, dynamic>> initialFoodData = [
{
    'name': 'Táo',
    'size': 150.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả',
    'calo': 52.0,
    'fat': 0.2,
    'carb': 14,
    'protein': 0.3,
    'type': 'Hoa quả'
  },
  {
    'name': 'Chuối',
    'size': 118.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả',
    'calo': 105.0,
    'fat': 0.3,
    'carb': 27,
    'protein': 1.3,
    'type': 'Hoa quả'
  },
  {
    'name': 'Dâu tây',
    'size': 12.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả',
    'calo': 4.0,
    'fat': 0.1,
    'carb': 0.9,
    'protein': 0.1,
    'type': 'Hoa quả'
  },
  {
    'name': 'Nho',
    'size': 151.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Chùm',
    'calo': 104.0,
    'fat': 0.3,
    'carb':27.2,
    'protein': 1.1,
    'type': 'Hoa quả'
  },
  {
    'name': 'Dưa hấu',
    'size': 280.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả',
    'calo': 85.0,
    'fat': 0.4,
    'carb': 21.6,
    'protein': 1.7,
    'type': 'Hoa quả'
  },
  {
    'name': 'Việt quất',
    'size': 148.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Chùm',
    'calo': 84.0,
    'fat': 0.5,
    'carb': 21.4,
    'protein': 1.1,
    'type': 'Hoa quả'
  },
  {
    'name': 'Xoài',
    'size': 336.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả',
    'calo': 201.0,
    'fat': 1.3,
    'carb': 53.3,
    'protein': 2.8,
    'type': 'Hoa quả'
  },
  {
    'name': 'Dứa',
    'size': 165.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả',
    'calo': 83.0,
    'fat': 21.6,
    'carb': 0.2,
    'protein': 0.9,
    'type': 'Hoa quả'
  },
  {
    'name': 'Bưởi', 
    'size': 350.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả', 
    'calo': 59.0,
    'fat': 0.4,
    'carb': 14.4,
    'protein': 1.4,
    'type': 'Hoa quả' 
  },
  {
    'name': 'Cam', 
    'size': 130.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả', 
    'calo': 47.0,
    'fat': 0.1,
    'carb': 11.3,
    'protein': 1.0,
    'type': 'Hoa quả' 
  },
  {
    'name': 'Quýt', 
    'size': 100.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả', 
    'calo': 42.0,
    'fat': 0.1,
    'carb': 10.3,
    'protein': 0.8,
    'type': 'Hoa quả' 
  },
  {
    'name': 'Bơ', 
    'size': 160.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả', 
    'calo': 160.0,
    'fat': 9.8,
    'carb': 15.3,
    'protein': 2.0,
    'type': 'Hoa quả' 
  },
  {
    'name': 'Măng cụt', 
    'size': 85.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả', 
    'calo': 62.0,
    'fat': 0.4,
    'carb': 15.3,
    'protein': 0.7,
    'type': 'Hoa quả' 
  },
  {
    'name': 'Dừa xiêm', 
    'size': 250.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả', 
    'calo': 154.0,
    'fat': 17.0,
    'carb': 24.0,
    'protein': 3.1,
    'type': 'Hoa quả' 
  },
  {
    'name': 'Thanh long', 
    'size': 180.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả', 
    'calo': 95.0,
    'fat': 0.4,
    'carb': 25.0,
    'protein': 0.8,
    'type': 'Hoa quả' 
  },
  
{
    'name': 'Ổi',
    'size': 250.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả',
    'calo': 49.0,
    'fat': 0.4,
    'carb': 12.0,
    'protein': 0.4,
    'type': 'Hoa quả'
  },
  {
    'name': 'Vú sữa', 
    'size': 160.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả', 
    'calo': 62.0,
    'fat': 0.4,
    'carb': 17,
    'protein': 0.8,
    'type': 'Hoa quả' 
  },
  {
    'name': 'Mận', 
    'size': 60.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả', 
    'calo': 17.0,
    'fat': 0.1,
    'carb': 4.3,
    'protein': 0.7,
    'type': 'Hoa quả' 
  },
  {
    'name': 'Dâu tây', 
    'size': 12.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả', 
    'calo': 4.0,
    'fat': 0.1,
    'carb': 0.9,
    'protein': 0.1,
    'type': 'Hoa quả' 
  },
  {
    'name': 'Sầu riêng', 
    'size': 240.0,
    'measure': 'grams',
    'number': 1,
    'name_word': 'Quả', 
    'calo': 155.0,
    'fat': 15.0,
    'carb': 39.0,
    'protein': 3.4,
    'type': 'Hoa quả' 
  },
  {
    'name': 'Cơm Tẻ',
    'size': 120,
    'measure': 'gram',
    'number': 1,
    'name_word': 'bát',
    'calo': 200,
    'fat': 1,
    'carb': 44,
    'protein': 5,
    'type': 'Cơm'
},
{
    'name': 'Cơm Tấm Bì',
    'number': 1,
    'name_word': 'Suất',
    'size': 279,
    'measure': 'gram',
    'calo': 627,
    'protein': 26,
    'fat': 19,
    'carb': 88,
    'type': 'Cơm'
},
{
    'name': 'Cơm Tấm Chả',
    'number': 1,
    'name_word': 'Suất',
    'size': 251,
    'measure': 'gram',
    'calo': 592,
    'protein': 17,
    'fat': 18,
    'carb': 91,
    'type': 'Cơm'
},
{
    'name': 'Cơm Tấm Sườn',
    'number': 1,
    'name_word': 'Suất',
    'size': 264,
    'measure': 'gram',
    'calo': 527,
    'protein': 21,
    'fat': 13,
    'carb': 82,
    'type': 'Cơm'
},
{
    'name': 'Cơm Rang Chay',
    'number': 1,
    'name_word': 'Suất',
    'size': 220,
    'measure': 'gram',
    'calo': 530,
    'protein': 15,
    'fat': 11,
    'carb': 93,
    'type': 'Cơm'
},
{
    'name': 'Canh Bắp Cải',
    'number': 1,
    'name_word': 'Phần',
    'size': 55,
    'measure': 'gram',
    'calo': 37,
    'protein': 2,
    'fat': 2,
    'carb': 3,
    'type': 'Canh'
},
{
    'name': 'Canh Cải Ngọt',
    'number': 1,
    'name_word': 'Phần',
    'size': 55,
    'measure': 'gram',
    'calo': 30,
    'protein': 2,
    'fat': 2,
    'carb': 1,
    'type': 'Canh'
},
{
    'name': 'Cháo Đậu Đỏ',
    'number': 1,
    'name_word': 'Suất',
    'size': 200,
    'measure': 'gram',
    'calo': 322,
    'protein': 11,
    'fat': 12,
    'carb': 44,
    'type': 'Cơm'
},
{
    'name': 'Cháo Vịt',
    'number': 1,
    'name_word': 'Suất',
    'size': 200,
    'measure': 'gram',
    'calo': 465,
    'protein': 25,
    'fat': 30,
    'carb': 25,
    'type': 'Cơm'
},
{
    'name': 'Cháo Tiết',
    'number': 1,
    'name_word': 'Suất',
    'size': 200,
    'measure': 'gram',
    'calo': 332,
    'protein': 22,
    'fat': 9,
    'carb': 41,
    'type': 'Cơm'
},
{
    'name': 'Cháo Lòng',
    'number': 1,
    'name_word': 'Suất',
    'size': 200,
    'measure': 'gram',
    'calo': 412,
    'protein': 31,
    'fat': 14,
    'carb': 42,
    'type': 'Cơm'
},
{
    'name': 'Canh Bí Đao',
    'number': 1,
    'name_word': 'Phần',
    'size': 55,
    'measure': 'gram',
    'calo': 29,
    'protein': 1,
    'fat': 2,
    'carb': 1,
    'type': 'Canh'
},
{
    'name': 'Canh Bầu',
    'number': 1,
    'name_word': 'Phần',
    'size': 55,
    'measure': 'gram',
    'calo': 30,
    'protein': 1,
    'fat': 2,
    'carb': 2,
    'type': 'Canh'
},
{
    'name': 'Canh Bí Ngô/Bí Rợ',
    'number': 1,
    'name_word': 'Phần',
    'size': 85,
    'measure': 'gram',
    'calo': 42,
    'protein': 1,
    'fat': 2,
    'carb': 5,
    'type': 'Canh'
},
{
    'name': 'Canh Khoai Mỡ',
    'number': 1,
    'name_word': 'Phần',
    'size': 45,
    'measure': 'gram',
    'calo': 51,
    'protein': 2,
    'fat': 1,
    'carb': 9,
    'type': 'Canh'
},
{
    'name': 'Canh Chua',
    'number': 1,
    'name_word': 'Phần',
    'size': 74,
    'measure': 'gram',
    'calo': 29,
    'protein': 2,
    'fat': 1,
    'carb': 3,
    'type': 'Canh'
},
{
    'name': 'Canh Mướp Đắng/Khổ Qua',
    'number': 1,
    'name_word': 'Phần',
    'size': 16,
    'measure': 'gram',
    'calo': 18,
    'protein': 1,
    'fat': 1,
    'carb': 1,
    'type': 'Canh'
},
{
    'name': 'Canh Hẹ',
    'number': 1,
    'name_word': 'Phần',
    'size': 50,
    'measure': 'gram',
    'calo': 33,
    'protein': 3,
    'fat': 2,
    'carb': 1,
    'type': 'Canh'
},
{
    'name': 'Canh Mướp',
    'number': 1,
    'name_word': 'Phần',
    'size': 55,
    'measure': 'gram',
    'calo': 31,
    'protein': 1,
    'fat': 2,
    'carb': 2,
    'type': 'Canh'
},
{
    'name': 'Canh Rau Ngót',
    'number': 1,
    'name_word': 'Phần',
    'size': 25,
    'measure': 'gram',
    'calo': 29,
    'protein': 2,
    'fat': 2,
    'carb': 1,
    'type': 'Canh'
},
{
    'name': 'Canh Rau Dền',
    'number': 1,
    'name_word': 'Phần',
    'size': 55,
    'measure': 'gram',
    'calo': 22,
    'protein': 1,
    'fat': 2,
    'carb': 0,
    'type': 'Canh'
},
{
    'name': 'Canh Rau Ngót Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 32,
    'measure': 'gram',
    'calo': 23,
    'protein': 2,
    'fat': 1,
    'carb': 1,
    'type': 'Canh'
},
{
    'name': 'Canh Kiểm',
    'number': 1,
    'name_word': 'Phần',
    'size': 100,
    'measure': 'gram',
    'calo': 291,
    'protein': 5,
    'fat': 13,
    'carb': 38,
    'type': 'Canh'
},
{
    'name': 'Canh Mướp Đắng/Khổ Qua Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 100,
    'measure': 'gram',
    'calo': 88,
    'protein': 5,
    'fat': 4,
    'carb': 8,
    'type': 'Canh'
},
{
    'name': 'Canh Chua Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 76,
    'measure': 'gram',
    'calo': 37,
    'protein': 2,
    'fat': 1,
    'carb': 5,
    'type': 'Canh'
},
{
    'name': 'Bún Thịt Nướng Chay',
    'number': 1,
    'name_word': 'Suất',
    'size': 250,
    'measure': 'gram',
    'calo': 451,
    'protein': 15,
    'fat': 14,
    'carb': 67,
    'type': 'Bún'
},
{
    'name': 'Bún Xào Chay',
    'number': 1,
    'name_word': 'Suất',
    'size': 250,
    'measure': 'gram',
    'calo': 570,
    'protein': 23,
    'fat': 28,
    'carb': 56,
    'type': 'Bún'
},
{
    'name': 'Bún Bò Huế Chay',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 479,
    'protein': 18,
    'fat': 16,
    'carb': 65,
    'type': 'Bún'
},
{
    'name': 'Bún Riêu Chay',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 482,
    'protein': 17,
    'fat': 17,
    'carb': 66,
    'type': 'Bún'
},
{
    'name': 'Bún Bò Giò Heo',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 622,
    'protein': 30,
    'fat': 31,
    'carb': 56,
    'type': 'Bún'
},
{
    'name': 'Bún Mắm',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 480,
    'protein': 28,
    'fat': 16,
    'carb': 57,
    'type': 'Bún'
},
{
    'name': 'Bún Măng',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 485,
    'protein': 21,
    'fat': 20,
    'carb': 56,
    'type': 'Bún'
},
{
    'name': 'Bún Mọc',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 514,
    'protein': 28,
    'fat': 19,
    'carb': 57,
    'type': 'Bún'
},
{
    'name': 'Bún Chả',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 598,
    'protein': 24,
    'fat': 21,
    'carb': 80,
    'type': 'Bún'
},
{
    'name': 'Bún Riêu Ốc',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 531,
    'protein': 28,
    'fat': 17,
    'carb': 66,
    'type': 'Bún'
},
{
    'name': 'Bún Riêu Cua',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 414,
    'protein': 18,
    'fat': 12,
    'carb': 58,
    'type': 'Bún'
},
{
    'name': 'Bún Thịt Nướng Chay',
    'number': 1,
    'name_word': 'Suất',
    'size': 250,
    'measure': 'gram',
    'calo': 451,
    'protein': 15,
    'fat': 14,
    'carb': 67,
    'type': 'Bún'
},
{
    'name': 'Bún Xào Chay',
    'number': 1,
    'name_word': 'Suất',
    'size': 250,
    'measure': 'gram',
    'calo': 570,
    'protein': 23,
    'fat': 28,
    'carb': 56,
    'type': 'Bún'
},
{
    'name': 'Bún Bò Huế Chay',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 479,
    'protein': 18,
    'fat': 16,
    'carb': 65,
    'type': 'Bún'
},
{
    'name': 'Bún Riêu Chay',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 482,
    'protein': 17,
    'fat': 17,
    'carb': 66,
    'type': 'Bún'
},
{
    'name': 'Bún Bò Giò Heo',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 622,
    'protein': 30,
    'fat': 31,
    'carb': 56,
    'type': 'Bún'
},
{
    'name': 'Bún Mắm',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 480,
    'protein': 28,
    'fat': 16,
    'carb': 57,
    'type': 'Bún'
},
{
    'name': 'Bún Măng',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 485,
    'protein': 21,
    'fat': 20,
    'carb': 56,
    'type': 'Bún'
},
{
    'name': 'Bún Mọc',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 514,
    'protein': 28,
    'fat': 19,
    'carb': 57,
    'type': 'Bún'
},
{
    'name': 'Bún Chả',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 598,
    'protein': 24,
    'fat': 21,
    'carb': 80,
    'type': 'Bún'
},
{
    'name': 'Bún Riêu Ốc',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 531,
    'protein': 28,
    'fat': 17,
    'carb': 66,
    'type': 'Bún'
},
{
    'name': 'Bún Riêu Cua',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 414,
    'protein': 18,
    'fat': 12,
    'carb': 58,
    'type': 'Bún'
},
{
    'name': 'Bánh Canh Cua',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 379,
    'protein': 21,
    'fat': 8,
    'carb': 54,
    'type': 'Bánh'
},
{
    'name': 'Bánh Canh Chân Giò',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 483,
    'protein': 19,
    'fat': 24,
    'carb': 49,
    'type': 'Bánh'
},
{
    'name': 'Bánh Canh Thịt Gà',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 346,
    'protein': 13,
    'fat': 11,
    'carb': 49,
    'type': 'Bánh'
},
{
    'name': 'Bánh Canh Thịt Lợn',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 322,
    'protein': 13,
    'fat': 9,
    'carb': 49,
    'type': 'Bánh'
},
{
    'name': 'Bánh Bao Nhân Chay',
    'number': 1,
    'name_word': 'Cái',
    'size': 72,
    'measure': 'gram',
    'calo': 220,
    'protein': 11,
    'fat': 5,
    'carb': 34,
    'type': 'Bánh'
},
{
    'name': 'Bánh Bò Hấp',
    'number': 1,
    'name_word': 'Cái',
    'size': 40,
    'measure': 'gram',
    'calo': 100,
    'protein': 1,
    'fat': 5,
    'carb': 14,
    'type': 'Bánh'
},
{
    'name': 'Bánh Chuối Hấp',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 506,
    'protein': 4,
    'fat': 14,
    'carb': 91,
    'type': 'Bánh'
},
{
    'name': 'Bánh Da Lợn',
    'number': 1,
    'name_word': 'Cái',
    'size': 125,
    'measure': 'gram',
    'calo': 364,
    'protein': 4,
    'fat': 12,
    'carb': 61,
    'type': 'Bánh'
},
{
    'name': 'Bánh Flan',
    'number': 1,
    'name_word': 'Cái',
    'size': 40,
    'measure': 'gram',
    'calo': 66,
    'protein': 2,
    'fat': 2,
    'carb': 11,
    'type': 'Bánh'
},
{
    'name': 'Bánh Bao Thập Cẩm',
    'number': 1,
    'name_word': 'Cái',
    'size': 200,
    'measure': 'gram',
    'calo': 328,
    'protein': 16,
    'fat': 8,
    'carb': 48,
    'type': 'Bánh'
},
{
    'name': 'Bánh Ít',
    'number': 1,
    'name_word': 'Cái',
    'size': 75,
    'measure': 'gram',
    'calo': 261,
    'protein': 4,
    'fat': 5,
    'carb': 50,
    'type': 'Bánh'
},
{
    'name': 'Bánh Chưng',
    'number': 1,
    'name_word': 'Phần',
    'size': 75,
    'measure': 'gram',
    'calo': 204,
    'protein': 8,
    'fat': 3,
    'carb': 37,
    'type': 'Bánh'
},
{
    'name': 'Bánh Chưng Ngọt',
    'number': 1,
    'name_word': 'Phần',
    'size': 75,
    'measure': 'gram',
    'calo': 224,
    'protein': 7,
    'fat': 1,
    'carb': 47,
    'type': 'Bánh'
},
{
    'name': 'Bánh Giò',
    'number': 1,
    'name_word': 'Cái',
    'size': 150,
    'measure': 'gram',
    'calo': 216,
    'protein': 9,
    'fat': 7,
    'carb': 29,
    'type': 'Bánh'
},
{
    'name': 'Bánh Bèo',
    'number': 1,
    'name_word': 'Phần',
    'size': 150,
    'measure': 'gram',
    'calo': 358,
    'protein': 13,
    'fat': 14,
    'carb': 45,
    'type': 'Bánh'
},
{
    'name': 'Bánh Bột Lọc',
    'number': 1,
    'name_word': 'Cái',
    'size': 20,
    'measure': 'gram',
    'calo': 60,
    'protein': 2,
    'fat': 3,
    'carb': 8,
    'type': 'Bánh'
},
{
    'name': 'Bánh Cuốn',
    'number': 1,
    'name_word': 'Phần',
    'size': 300,
    'measure': 'gram',
    'calo': 590,
    'protein': 26,
    'fat': 26,
    'carb': 64,
    'type': 'Bánh'
},
{
    'name': 'Bánh Chuối',
    'number': 1,
    'name_word': 'Cái',
    'size': 150,
    'measure': 'gram',
    'calo': 139,
    'protein': 1,
    'fat': 10,
    'carb': 12,
    'type': 'Bánh'
},
{
    'name': 'Bánh Mì',
    'number': 1,
    'name_word': 'Ổ',
    'size': 100,
    'measure': 'gram',
    'calo': 239,
    'protein': 8,
    'fat': 1,
    'carb': 51,
    'type': 'Bánh'
},
{
    'name': 'Bánh Sandwich',
    'number': 1,
    'name_word': 'Lát',
    'size': 25,
    'measure': 'gram',
    'calo': 89,
    'protein': 3,
    'fat': 1,
    'carb': 17,
    'type': 'Bánh'
},
{
    'name': 'Bánh Su Kem',
    'number': 1,
    'name_word': 'Cái',
    'size': 50,
    'measure': 'gram',
    'calo': 112,
    'protein': 2,
    'fat': 7,
    'carb': 10,
    'type': 'Bánh'
},
{
    'name': 'Bánh Mì Chà Bông',
    'number': 1,
    'name_word': 'Ổ',
    'size': 150,
    'measure': 'gram',
    'calo': 337,
    'protein': 18,
    'fat': 5,
    'carb': 54,
    'type': 'Bánh'
},
{
    'name': 'Bánh Mì Kẹp Thập Cẩm',
    'number': 1,
    'name_word': 'Ổ',
    'size': 200,
    'measure': 'gram',
    'calo': 431,
    'protein': 20,
    'fat': 14,
    'carb': 56,
    'type': 'Bánh'
},
{
    'name': 'Bánh Sandwich Kẹp Thịt',
    'number': 1,
    'name_word': 'Phần',
    'size': 150,
    'measure': 'gram',
    'calo': 468,
    'protein': 19,
    'fat': 26,
    'carb': 39,
    'type': 'Bánh'
},
{
    'name': 'Bánh Kem Xốp',
    'number': 1,
    'name_word': 'Cái',
    'size': 20,
    'measure': 'gram',
    'calo': 98,
    'protein': 2,
    'fat': 5,
    'carb': 12,
    'type': 'Bánh'
},
{
    'name': 'Bánh Bông Lan',
    'number': 1,
    'name_word': 'Cái',
    'size': 60,
    'measure': 'gram',
    'calo': 217,
    'protein': 4,
    'fat': 12,
    'carb': 22,
    'type': 'Bánh'
},
{
    'name': 'Bánh Nướng Trung Thu',
    'number': 1,
    'name_word': 'Phần',
    'size': 15,
    'measure': 'gram',
    'calo': 96,
    'protein': 3,
    'fat': 5,
    'carb': 10,
    'type': 'Bánh'
},
{
    'name': 'Bánh Dẻo Trung Thu',
    'number': 1,
    'name_word': 'Phần',
    'size': 15,
    'measure': 'gram',
    'calo': 78,
    'protein': 1,
    'fat': 1,
    'carb': 16,
    'type': 'Bánh'
},
{
    'name': 'Bánh Khúc',
    'number': 1,
    'name_word': 'Cái',
    'size': 150,
    'measure': 'gram',
    'calo': 395,
    'protein': 10,
    'fat': 11,
    'carb': 65,
    'type': 'Bánh'
},
{
    'name': 'Phở Bò Tái Bình Dân',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 413,
    'protein': 18,
    'fat': 12,
    'carb': 59,
    'type': 'Phở'
},
{
    'name': 'Phở Bò Chín Bình Dân',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 430,
    'protein': 21,
    'fat': 12,
    'carb': 59,
    'type': 'Phở'
},
{
    'name': 'Phở Bò Tái Trung Bình',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 431,
    'protein': 21,
    'fat': 12,
    'carb': 59,
    'type': 'Phở'
},
{
    'name': 'Phở Bò Chín Trung Bình',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 456,
    'protein': 26,
    'fat': 13,
    'carb': 59,
    'type': 'Phở'
},
{
    'name': 'Phở Bò Tái Đặc Biệt',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 543,
    'protein': 36,
    'fat': 15,
    'carb': 59,
    'type': 'Phở'
},
{
    'name': 'Phở Bò Chín Đặc Biệt',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 517,
    'protein': 31,
    'fat': 14,
    'carb': 59,
    'type': 'Phở'
},
{
    'name': 'Phở Bò Viên',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 431,
    'protein': 16,
    'fat': 14,
    'carb': 60,
    'type': 'Phở'
},
{
    'name': 'Phở Gà Bình Dân',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 456,
    'protein': 19,
    'fat': 16,
    'carb': 59,
    'type': 'Phở'
},
{
    'name': 'Phở Gà Trung Bình',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 483,
    'protein': 21,
    'fat': 18,
    'carb': 59,
    'type': 'Phở'
},
{
    'name': 'Phở Gà Đặc Biệt',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 561,
    'protein': 27,
    'fat': 21,
    'carb': 67,
    'type': 'Phở'
},
{
    'name': 'Chè Đậu Xanh',
    'number': 1,
    'name_word': 'Bát',
    'size': 150,
    'measure': 'gram',
    'calo': 359,
    'protein': 13,
    'fat': 10,
    'carb': 53,
    'type': 'Chè'
},
{
    'name': 'Chè Khoai Môn',
    'number': 1,
    'name_word': 'Bát',
    'size': 150,
    'measure': 'gram',
    'calo': 385,
    'protein': 5,
    'fat': 11,
    'carb': 67,
    'type': 'Chè'
},
{
    'name': 'Chè Trôi Nước',
    'number': 1,
    'name_word': 'Bát',
    'size': 150,
    'measure': 'gram',
    'calo': 513,
    'protein': 12,
    'fat': 12,
    'carb': 90,
    'type': 'Chè'
},
{
    'name': 'Chè Mè Đen',
    'number': 1,
    'name_word': 'Bát',
    'size': 150,
    'measure': 'gram',
    'calo': 338,
    'protein': 6,
    'fat': 18,
    'carb': 38,
    'type': 'Chè'
},
{
    'name': 'Tào Phớ',
    'number': 1,
    'name_word': 'Bát',
    'size': 150,
    'measure': 'gram',
    'calo': 241,
    'protein': 7,
    'fat': 7,
    'carb': 38,
    'type': 'Chè'
},
{
    'name': 'Chè Đậu Đen',
    'number': 1,
    'name_word': 'Cốc',
    'size': 150,
    'measure': 'gram',
    'calo': 419,
    'protein': 13,
    'fat': 10,
    'carb': 70,
    'type': 'Chè'
},
{
    'name': 'Chè Long Nhãn',
    'number': 1,
    'name_word': 'Cốc',
    'size': 150,
    'measure': 'gram',
    'calo': 199,
    'protein': 2,
    'fat': 0,
    'carb': 47,
    'type': 'Chè'
},
{
    'name': 'Chè Thập Cẩm',
    'number': 1,
    'name_word': 'Cốc',
    'size': 150,
    'measure': 'gram',
    'calo': 268,
    'protein': 6,
    'fat': 1,
    'carb': 60,
    'type': 'Chè'
},
{
    'name': 'Hủ Tiếu Bò Kho Chay',
    'number': 1,
    'name_word': 'Suất',
    'size': 250,
    'measure': 'gram',
    'calo': 410,
    'protein': 17,
    'fat': 13,
    'carb': 55,
    'type': 'Mì'
},
{
    'name': 'Mì Bò Viên Chay',
    'number': 1,
    'name_word': 'Suất',
    'size': 250,
    'measure': 'gram',
    'calo': 456,
    'protein': 20,
    'fat': 14,
    'carb': 62,
    'type': 'Mì'
},
{
    'name': 'Mì Căn Xào',
    'number': 1,
    'name_word': 'Suất',
    'size': 115,
    'measure': 'gram',
    'calo': 299,
    'protein': 8,
    'fat': 6,
    'carb': 54,
    'type': 'Mì'
},
{
    'name': 'Hủ Tiếu Bò Kho',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 538,
    'protein': 34,
    'fat': 26,
    'carb': 42,
    'type': 'Mì'
},
{
    'name': 'Hủ Tiếu Nam Vang',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 400,
    'protein': 24,
    'fat': 15,
    'carb': 43,
    'type': 'Mì'
},
{
    'name': 'Hủ Tiếu Thịt Lợn',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 361,
    'protein': 14,
    'fat': 13,
    'carb': 48,
    'type': 'Mì'
},
{
    'name': 'Mì Thịt Lợn',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 415,
    'protein': 19,
    'fat': 8,
    'carb': 66,
    'type': 'Mì'
},
{
    'name': 'Hoành Thánh',
    'number': 1,
    'name_word': 'Suất',
    'size': 75,
    'measure': 'gram',
    'calo': 248,
    'protein': 12,
    'fat': 7,
    'carb': 32,
    'type': 'Mì'
},
{
    'name': 'Hủ Tiếu Xào',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 646,
    'protein': 41,
    'fat': 26,
    'carb': 63,
    'type': 'Mì'
},
{
    'name': 'Mì Xào',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 638,
    'protein': 42,
    'fat': 29,
    'carb': 52,
    'type': 'Mì'
},
{
    'name': 'Mì Quảng',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 541,
    'protein': 22,
    'fat': 20,
    'carb': 67,
    'type': 'Mì'
},
{
    'name': 'Mì Vịt Tiềm',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 776,
    'protein': 33,
    'fat': 43,
    'carb': 65,
    'type': 'Mì'
},
{
    'name': 'Miến Gà',
    'number': 1,
    'name_word': 'Suất',
    'size': 300,
    'measure': 'gram',
    'calo': 635,
    'protein': 18,
    'fat': 18,
    'carb': 100,
    'type': 'Mì'
},
{
    'name': 'Nui Xào Thịt Lợn',
    'number': 1,
    'name_word': 'Suất',
    'size': 200,
    'measure': 'gram',
    'calo': 414,
    'protein': 18,
    'fat': 9,
    'carb': 61,
    'type': 'Mì'
},
{
    'name': 'Nui Chiên',
    'number': 1,
    'name_word': 'Suất',
    'size': 200,
    'measure': 'gram',
    'calo': 523,
    'protein': 18,
    'fat': 24,
    'carb': 58,
    'type': 'Mì'
},
{
    'name': 'Cá Bạc Má Kho',
    'number': 1,
    'name_word': 'Con',
    'size': 100,
    'measure': 'gram',
    'calo': 167,
    'protein': 21,
    'fat': 5,
    'carb': 9,
    'type': 'Cá'
},
{
    'name': 'Cá Đối Kho',
    'number': 1,
    'name_word': 'Con',
    'size': 50,
    'measure': 'gram',
    'calo': 82,
    'protein': 10,
    'fat': 3,
    'carb': 4,
    'type': 'Cá'
},
{
    'name': 'Cá Hú Kho',
    'number': 1,
    'name_word': 'Phần',
    'size': 87,
    'measure': 'gram',
    'calo': 184,
    'protein': 16,
    'fat': 10,
    'carb': 9,
    'type': 'Cá'
},
{
    'name': 'Cá Lóc/Cá Quả Kho',
    'number': 1,
    'name_word': 'Phần',
    'size': 81,
    'measure': 'gram',
    'calo': 131,
    'protein': 16,
    'fat': 4,
    'carb': 9,
    'type': 'Cá'
},
{
    'name': 'Cá Ngừ Kho',
    'number': 1,
    'name_word': 'Phần',
    'size': 80,
    'measure': 'gram',
    'calo': 122,
    'protein': 18,
    'fat': 2,
    'carb': 9,
    'type': 'Cá'
},
{
    'name': 'Cá Chép Chưng Tương',
    'number': 1,
    'name_word': 'Phần',
    'size': 106,
    'measure': 'gram',
    'calo': 156,
    'protein': 16,
    'fat': 7,
    'carb': 8,
    'type': 'Cá'
},
{
    'name': 'Cá Chim Chiên',
    'number': 1,
    'name_word': 'Phần',
    'size': 67,
    'measure': 'gram',
    'calo': 111,
    'protein': 11,
    'fat': 8,
    'carb': 0,
    'type': 'Cá'
},
{
    'name': 'Cá Bạc Má Chiên',
    'number': 1,
    'name_word': 'Con',
    'size': 73,
    'measure': 'gram',
    'calo': 135,
    'protein': 13,
    'fat': 9,
    'carb': 0,
    'type': 'Cá'
},
{
    'name': 'Cá Đối Chiên',
    'number': 1,
    'name_word': 'Con',
    'size': 56,
    'measure': 'gram',
    'calo': 108,
    'protein': 10,
    'fat': 8,
    'carb': 0,
    'type': 'Cá'
},
{
    'name': 'Cá Cơm Lăn Bột Chiên',
    'number': 1,
    'name_word': 'Phần',
    'size': 72,
    'measure': 'gram',
    'calo': 195,
    'protein': 10,
    'fat': 10,
    'carb': 17,
    'type': 'Cá'
},
{
    'name': 'Cá Lóc/Cá Quả Chiên',
    'number': 1,
    'name_word': 'Phần',
    'size': 92,
    'measure': 'gram',
    'calo': 169,
    'protein': 15,
    'fat': 12,
    'carb': 0,
    'type': 'Cá'
},
{
    'name': 'Cá Trê Chiên',
    'number': 1,
    'name_word': 'Phần',
    'size': 85,
    'measure': 'gram',
    'calo': 219,
    'protein': 12,
    'fat': 19,
    'carb': 0,
    'type': 'Cá'
},
{
    'name': 'Chim Cút Chiên',
    'number': 1,
    'name_word': 'Con',
    'size': 70,
    'measure': 'gram',
    'calo': 204,
    'protein': 11,
    'fat': 17,
    'carb': 2,
    'type': 'Cá'
},
{
    'name': 'Chả Cá Chiên',
    'number': 1,
    'name_word': 'Miếng',
    'size': 73,
    'measure': 'gram',
    'calo': 133,
    'protein': 11,
    'fat': 10,
    'carb': 0,
    'type': 'Cá'
},
{
    'name': 'Cá Cơm Lăn Bột Chiên Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 75,
    'measure': 'gram',
    'calo': 316,
    'protein': 7,
    'fat': 17,
    'carb': 33,
    'type': 'Cá'
},
{
    'name': 'Cá Kho Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 160,
    'measure': 'gram',
    'calo': 105,
    'protein': 4,
    'fat': 5,
    'carb': 21,
    'type': 'Cá'
},
{
    'name': 'Thịt Kho',
    'number': 1,
    'name_word': 'Phần',
    'size': 108,
    'measure': 'gram',
    'calo': 200,
    'protein': 21,
    'fat': 8,
    'carb': 12,
    'type': 'Thịt'
},
{
    'name': 'Thịt Kho Trứng',
    'number': 1,
    'name_word': 'Phần',
    'size': 125,
    'measure': 'gram',
    'calo': 315,
    'protein': 19,
    'fat': 23,
    'carb': 8,
    'type': 'Thịt'
},
{
    'name': 'Thịt Quay',
    'number': 1,
    'name_word': 'Phần',
    'size': 56,
    'measure': 'gram',
    'calo': 146,
    'protein': 9,
    'fat': 12,
    'carb': 0,
    'type': 'Thịt'
},
{
    'name': 'Thịt Bò Xào Đậu Que',
    'number': 1,
    'name_word': 'Phần',
    'size': 180,
    'measure': 'gram',
    'calo': 195,
    'protein': 17,
    'fat': 7,
    'carb': 17,
    'type': 'Thịt'
},
{
    'name': 'Thịt Bò Xào Giá',
    'number': 1,
    'name_word': 'Phần',
    'size': 165,
    'measure': 'gram',
    'calo': 143,
    'protein': 16,
    'fat': 7,
    'carb': 5,
    'type': 'Thịt'
},
{
    'name': 'Thịt Bò Xào Hành Tây',
    'number': 1,
    'name_word': 'Phần',
    'size': 125,
    'measure': 'gram',
    'calo': 132,
    'protein': 12,
    'fat': 7,
    'carb': 6,
    'type': 'Thịt'
},
{
    'name': 'Thịt Bò Xào Nấm Rơm',
    'number': 1,
    'name_word': 'Phần',
    'size': 140,
    'measure': 'gram',
    'calo': 152,
    'protein': 14,
    'fat': 10,
    'carb': 3,
    'type': 'Thịt'
},
{
    'name': 'Thịt Bò Xào Khoai Tây',
    'number': 1,
    'name_word': 'Phần',
    'size': 150,
    'measure': 'gram',
    'calo': 246,
    'protein': 12,
    'fat': 13,
    'carb': 20,
    'type': 'Thịt'
},
{
    'name': 'Thịt Bò Xào Măng',
    'number': 1,
    'name_word': 'Phần',
    'size': 110,
    'measure': 'gram',
    'calo': 104,
    'protein': 11,
    'fat': 7,
    'carb': 0,
    'type': 'Thịt'
},
{
    'name': 'Thịt Lợn Xào Đậu Que',
    'number': 1,
    'name_word': 'Phần',
    'size': 200,
    'measure': 'gram',
    'calo': 240,
    'protein': 21,
    'fat': 10,
    'carb': 17,
    'type': 'Thịt'
},
{
    'name': 'Thịt Lợn Xào Giá',
    'number': 1,
    'name_word': 'Phần',
    'size': 190,
    'measure': 'gram',
    'calo': 188,
    'protein': 19,
    'fat': 10,
    'carb': 5,
    'type': 'Thịt'
},
{
    'name': 'Thịt Quay Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 75,
    'measure': 'gram',
    'calo': 250,
    'protein': 7,
    'fat': 14,
    'carb': 24,
    'type': 'Thịt'
},
{
    'name': 'Thịt Kho Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 100,
    'measure': 'gram',
    'calo': 312,
    'protein': 23,
    'fat': 16,
    'carb': 20,
    'type': 'Thịt'
},
{
    'name': 'Trứng Vịt',
    'number': 1,
    'name_word': 'Quả',
    'size': 55,
    'measure': 'gram',
    'calo': 90,
    'protein': 6,
    'fat': 7,
    'carb': 1,
    'type': 'Trứng'
},
{
    'name': 'Trứng Vịt Lộn',
    'number': 1,
    'name_word': 'Quả',
    'size': 55,
    'measure': 'gram',
    'calo': 98,
    'protein': 7,
    'fat': 7,
    'carb': 2,
    'type': 'Trứng'
},
{
    'name': 'Trứng Gà',
    'number': 1,
    'name_word': 'Quả',
    'size': 40,
    'measure': 'gram',
    'calo': 58,
    'protein': 5,
    'fat': 4,
    'carb': 0,
    'type': 'Trứng'
},
{
    'name': 'Trứng Cút',
    'number': 1,
    'name_word': 'Quả',
    'size': 10,
    'measure': 'gram',
    'calo': 17,
    'protein': 2,
    'fat': 1,
    'carb': 0,
    'type': 'Trứng'
},
{
    'name': 'Trứng Muối',
    'number': 1,
    'name_word': 'Quả',
    'size': 50,
    'measure': 'gram',
    'calo': 90,
    'protein': 6,
    'fat': 7,
    'carb': 1,
    'type': 'Trứng'
},
{
    'name': 'Trứng Ngỗng',
    'number': 1,
    'name_word': 'Quả',
    'size': 144,
    'measure': 'gram',
    'calo': 210,
    'protein': 15,
    'fat': 16,
    'carb': 1,
    'type': 'Trứng'
},
{
    'name': 'Sữa Bột',
    'number': 1,
    'name_word': 'Cốc',
    'size': 220,
    'measure': 'gram',
    'calo': 148,
    'protein': 2,
    'fat': 3,
    'carb': 7,
    'type': 'Sữa'
},
{
    'name': 'Sữa Bột Tách Béo',
    'number': 1,
    'name_word': 'Cốc',
    'size': 220,
    'measure': 'gram',
    'calo': 77,
    'protein': 7,
    'fat': 0,
    'carb': 12,
    'type': 'Sữa'
},
{
    'name': 'Sữa Tươi',
    'number': 1,
    'name_word': 'Hộp',
    'size': 180,
    'measure': 'gram',
    'calo': 152,
    'protein': 7,
    'fat': 6,
    'carb': 18,
    'type': 'Sữa'
},
{
    'name': 'Sữa Đậu Nành',
    'number': 1,
    'name_word': 'Cốc',
    'size': 180,
    'measure': 'gram',
    'calo': 136,
    'protein': 6,
    'fat': 3,
    'carb': 15,
    'type': 'Sữa'
},
{
    'name': 'Sữa Chua',
    'number': 1,
    'name_word': 'Hộp',
    'size': 100,
    'measure': 'gram',
    'calo': 137,
    'protein': 4,
    'fat': 4,
    'carb': 22,
    'type': 'Sữa'
},
{
    'name': 'Sữa Chua Uống',
    'number': 1,
    'name_word': 'Hộp',
    'size': 180,
    'measure': 'gram',
    'calo': 134,
    'protein': 3,
    'fat': 2,
    'carb': 28,
    'type': 'Sữa'
},
{
    'name': 'Sữa Đặc',
    'number': 1,
    'name_word': 'Phần',
    'size': 100,
    'measure': 'gram',
    'calo': 88,
    'protein': 2,
    'fat': 2,
    'carb': 15,
    'type': 'Sữa'
},
{
    'name': 'Phô Mai',
    'number': 1,
    'name_word': 'Miếng',
    'size': 18,
    'measure': 'gram',
    'calo': 67,
    'protein': 5,
    'fat': 5,
    'carb': 0,
    'type': 'Sữa'
},
{
    'name': 'Bột Ngũ Cốc',
    'number': 1,
    'name_word': 'Gói',
    'size': 100,
    'measure': 'gram',
    'calo': 402,
    'protein': 12,
    'fat': 6,
    'carb': 74,
    'type': 'Sữa'
},
{
    'name': 'Xíu Mại',
    'number': 1,
    'name_word': 'Phần',
    'size': 100,
    'measure': 'gram',
    'calo': 104,
    'protein': 12,
    'fat': 4,
    'carb': 5,
    'type': 'Thịt'
},
{
    'name': 'Chả Lụa',
    'number': 1,
    'name_word': 'Phần',
    'size': 47,
    'measure': 'gram',
    'calo': 102,
    'protein': 12,
    'fat': 5,
    'carb': 4,
    'type': 'Thịt'
},
{
    'name': 'Chả Viên',
    'number': 1,
    'name_word': 'Phần',
    'size': 77,
    'measure': 'gram',
    'calo': 100,
    'protein': 15,
    'fat': 3,
    'carb': 4,
    'type': 'Thịt'
},
{
    'name': 'Sườn Ram',
    'number': 1,
    'name_word': 'Phần',
    'size': 57,
    'measure': 'gram',
    'calo': 155,
    'protein': 11,
    'fat': 11,
    'carb': 3,
    'type': 'Thịt'
},
{
    'name': 'Sườn Nướng',
    'number': 1,
    'name_word': 'Phần',
    'size': 57,
    'measure': 'gram',
    'calo': 111,
    'protein': 10,
    'fat': 7,
    'carb': 1,
    'type': 'Thịt'
},
{
    'name': 'Chả Trứng Chưng',
    'number': 1,
    'name_word': 'Phần',
    'size': 71,
    'measure': 'gram',
    'calo': 195,
    'protein': 11,
    'fat': 14,
    'carb': 6,
    'type': 'Thịt'
},
{
    'name': 'Chả Giò Chiên/Nem Chiên',
    'number': 1,
    'name_word': 'Cái',
    'size': 20,
    'measure': 'gram',
    'calo': 41,
    'protein': 2,
    'fat': 2,
    'carb': 4,
    'type': 'Thịt'
},
{
    'name': 'Lạp Xưởng Chiên',
    'number': 1,
    'name_word': 'Cái',
    'size': 50,
    'measure': 'gram',
    'calo': 293,
    'protein': 10,
    'fat': 28,
    'carb': 1,
    'type': 'Thịt'
},
{
    'name': 'Đậu Phụ Nhồi Thịt',
    'number': 1,
    'name_word': 'Phần',
    'size': 76,
    'measure': 'gram',
    'calo': 164,
    'protein': 9,
    'fat': 13,
    'carb': 3,
    'type': 'Thịt'
},
{
    'name': 'Chân Giò Kho Củ Cải',
    'number': 1,
    'name_word': 'Phần',
    'size': 170,
    'measure': 'gram',
    'calo': 276,
    'protein': 19,
    'fat': 19,
    'carb': 7,
    'type': 'Thịt'
},
{
    'name': 'Gà Kho Gừng',
    'number': 1,
    'name_word': 'Phần',
    'size': 124,
    'measure': 'gram',
    'calo': 301,
    'protein': 22,
    'fat': 19,
    'carb': 10,
    'type': 'Thịt'
},
{
    'name': 'Bì Cuốn',
    'number': 1,
    'name_word': 'Phần',
    'size': 50,
    'measure': 'gram',
    'calo': 116,
    'protein': 10,
    'fat': 4,
    'carb': 11,
    'type': 'Thịt'
},
{
    'name': 'Bò Bía',
    'number': 1,
    'name_word': 'Phần',
    'size': 56,
    'measure': 'gram',
    'calo': 93,
    'protein': 6,
    'fat': 4,
    'carb': 8,
    'type': 'Thịt'
},
{
    'name': 'Gỏi Cuốn',
    'number': 1,
    'name_word': 'Phần',
    'size': 45,
    'measure': 'gram',
    'calo': 147,
    'protein': 8,
    'fat': 5,
    'carb': 18,
    'type': 'Thịt'
},
{
    'name': 'Gỏi Bò Khô',
    'number': 1,
    'name_word': 'Phần',
    'size': 120,
    'measure': 'gram',
    'calo': 268,
    'protein': 16,
    'fat': 12,
    'carb': 25,
    'type': 'Thịt'
},
{
    'name': 'Bò Cuốn Lá Lốt',
    'number': 1,
    'name_word': 'Phần',
    'size': 70,
    'measure': 'gram',
    'calo': 280,
    'protein': 16,
    'fat': 4,
    'carb': 44,
    'type': 'Thịt'
},
{
    'name': 'Bò Cuốn Mỡ Chài',
    'number': 1,
    'name_word': 'Phần',
    'size': 80,
    'measure': 'gram',
    'calo': 393,
    'protein': 20,
    'fat': 15,
    'carb': 44,
    'type': 'Thịt'
},
{
    'name': 'Đùi Gà Chiên Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 75,
    'measure': 'gram',
    'calo': 173,
    'protein': 11,
    'fat': 12,
    'carb': 5,
    'type': 'Thịt'
},
{
    'name': 'Đậu Phụ Nhồi Thịt Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 100,
    'measure': 'gram',
    'calo': 196,
    'protein': 9,
    'fat': 14,
    'carb': 8,
    'type': 'Thịt'
},
{
    'name': 'Cà Chua Nhồi Thịt Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 100,
    'measure': 'gram',
    'calo': 131,
    'protein': 7,
    'fat': 7,
    'carb': 9,
    'type': 'Thịt'
},
{
    'name': 'Đậu Phụ Sốt Cà Chua',
    'number': 1,
    'name_word': 'Phần',
    'size': 100,
    'measure': 'gram',
    'calo': 119,
    'protein': 9,
    'fat': 7,
    'carb': 6,
    'type': 'Thịt'
},
{
    'name': 'Tép Rang',
    'number': 1,
    'name_word': 'Phần',
    'size': 53,
    'measure': 'gram',
    'calo': 101,
    'protein': 6,
    'fat': 7,
    'carb': 5,
    'type': ''
},
{
    'name': 'Mực Xào Xả Ớt',
    'number': 1,
    'name_word': 'Phần',
    'size': 195,
    'measure': 'gram',
    'calo': 184,
    'protein': 31,
    'fat': 7,
    'carb': 0,
    'type': ''
},
{
    'name': 'Mực Xào Thập Cẩm',
    'number': 1,
    'name_word': 'Phần',
    'size': 200,
    'measure': 'gram',
    'calo': 136,
    'protein': 17,
    'fat': 6,
    'carb': 4,
    'type': ''
},
{
    'name': 'Tàu Hủ Ky Chiên',
    'number': 1,
    'name_word': 'Phần',
    'size': 75,
    'measure': 'gram',
    'calo': 306,
    'protein': 37,
    'fat': 15,
    'carb': 5,
    'type': ''
},
{
    'name': 'Tôm Lăn Bột Chiên Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 75,
    'measure': 'gram',
    'calo': 247,
    'protein': 3,
    'fat': 10,
    'carb': 36,
    'type': ''
},
{
    'name': 'Tôm Sốt Cà Chua Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 100,
    'measure': 'gram',
    'calo': 248,
    'protein': 13,
    'fat': 9,
    'carb': 29,
    'type': ''
},
{
    'name': 'Xôi Gấc',
    'number': 1,
    'name_word': 'Phần',
    'size': 150,
    'measure': 'gram',
    'calo': 589,
    'protein': 12,
    'fat': 14,
    'carb': 102,
    'type': 'Xôi'
},
{
    'name': 'Xôi Lạc',
    'number': 1,
    'name_word': 'Phần',
    'size': 150,
    'measure': 'gram',
    'calo': 659,
    'protein': 20,
    'fat': 28,
    'carb': 81,
    'type': 'Xôi'
},
{
    'name': 'Xôi Đậu Đen',
    'number': 1,
    'name_word': 'Phần',
    'size': 150,
    'measure': 'gram',
    'calo': 550,
    'protein': 17,
    'fat': 11,
    'carb': 96,
    'type': 'Xôi'
},
{
    'name': 'Xôi Đậu Xanh',
    'number': 1,
    'name_word': 'Phần',
    'size': 150,
    'measure': 'gram',
    'calo': 532,
    'protein': 15,
    'fat': 11,
    'carb': 93,
    'type': 'Xôi'
},
{
    'name': 'Xôi Thịt',
    'number': 1,
    'name_word': 'Phần',
    'size': 150,
    'measure': 'gram',
    'calo': 499,
    'protein': 18,
    'fat': 19,
    'carb': 65,
    'type': 'Xôi'
},
{
    'name': 'Xôi Xéo',
    'number': 1,
    'name_word': 'Phần',
    'size': 150,
    'measure': 'gram',
    'calo': 313,
    'protein': 8,
    'fat': 8,
    'carb': 51,
    'type': 'Xôi'
},
{
    'name': 'Kẹo Sôcôla',
    'number': 1,
    'name_word': 'Viên',
    'size': 5,
    'measure': 'gram',
    'calo': 19,
    'protein': 0,
    'fat': 0,
    'carb': 4,
    'type': 'Kẹo'
},
{
    'name': 'Kẹo Sữa',
    'number': 1,
    'name_word': 'Viên',
    'size': 5,
    'measure': 'gram',
    'calo': 13,
    'protein': 0,
    'fat': 0,
    'carb': 3,
    'type': 'Kẹo'
},
{
    'name': 'Kẹo Dừa',
    'number': 1,
    'name_word': 'Viên',
    'size': 10,
    'measure': 'gram',
    'calo': 31,
    'protein': 0,
    'fat': 1,
    'carb': 6,
    'type': 'Kẹo'
},
{
    'name': 'Kẹo Dẻo',
    'number': 1,
    'name_word': 'Viên',
    'size': 5,
    'measure': 'gram',
    'calo': 9,
    'protein': 0,
    'fat': 0,
    'carb': 2,
    'type': 'Kẹo'
},
{
    'name': 'Mè Xửng',
    'number': 1,
    'name_word': 'Miếng',
    'size': 25,
    'measure': 'gram',
    'calo': 122,
    'protein': 3,
    'fat': 6,
    'carb': 13,
    'type': 'Kẹo'
},
{
    'name': 'Kẹo Lạc',
    'number': 1,
    'name_word': 'Miếng',
    'size': 25,
    'measure': 'gram',
    'calo': 117,
    'protein': 3,
    'fat': 4,
    'carb': 17,
    'type': 'Kẹo'
},
{
    'name': 'Hủ Tiếu Bò Kho Chay',
    'number': 1,
    'name_word': 'Suất',
    'size': 250,
    'measure': 'gram',
    'calo': 410,
    'protein': 17,
    'fat': 13,
    'carb': 55,
    'type': ''
},
{
    'name': 'Mắm Thái Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 100,
    'measure': 'gram',
    'calo': 167,
    'protein': 11,
    'fat': 7,
    'carb': 14,
    'type': ''
},
{
    'name': 'Sườn Ram Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 80,
    'measure': 'gram',
    'calo': 274,
    'protein': 8,
    'fat': 6,
    'carb': 47,
    'type': ''
},
{
    'name': 'Sườn Nướng Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 50,
    'measure': 'gram',
    'calo': 123,
    'protein': 11,
    'fat': 7,
    'carb': 4,
    'type': ''
},
{
    'name': 'Đậu Phụ Chiên',
    'number': 1,
    'name_word': 'Phần',
    'size': 110,
    'measure': 'gram',
    'calo': 148,
    'protein': 12,
    'fat': 11,
    'carb': 1,
    'type': ''
},
{
    'name': 'Bầu Xào Trứng',
    'number': 1,
    'name_word': 'Phần',
    'size': 160,
    'measure': 'gram',
    'calo': 109,
    'protein': 4,
    'fat': 9,
    'carb': 4,
    'type': ''
},
{
    'name': 'Mướp Đắng/Khổ Qua Xào Trứng',
    'number': 1,
    'name_word': 'Phần',
    'size': 170,
    'measure': 'gram',
    'calo': 114,
    'protein': 5,
    'fat': 9,
    'carb': 5,
    'type': ''
},
{
    'name': 'Gỏi Bắp Chuối',
    'number': 1,
    'name_word': 'Phần',
    'size': 150,
    'measure': 'gram',
    'calo': 124,
    'protein': 5,
    'fat': 6,
    'carb': 11,
    'type': ''
},
{
    'name': 'Gỏi Ngó Sen Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 200,
    'measure': 'gram',
    'calo': 286,
    'protein': 12,
    'fat': 9,
    'carb': 38,
    'type': ''
},
{
    'name': 'Cà Tím Nướng',
    'number': 1,
    'name_word': 'Phần',
    'size': 150,
    'measure': 'gram',
    'calo': 33,
    'protein': 2,
    'fat': 0,
    'carb': 7,
    'type': ''
},
{
    'name': 'Món Xào Thập Cẩm',
    'number': 1,
    'name_word': 'Phần',
    'size': 240,
    'measure': 'gram',
    'calo': 142,
    'protein': 7,
    'fat': 6,
    'carb': 15,
    'type': ''
},
{
    'name': 'Món Kho Thập Cẩm Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 160,
    'measure': 'gram',
    'calo': 141,
    'protein': 9,
    'fat': 6,
    'carb': 13,
    'type': ''
},
{
    'name': 'Mít Non Kho',
    'number': 1,
    'name_word': 'Phần',
    'size': 150,
    'measure': 'gram',
    'calo': 100,
    'protein': 4,
    'fat': 5,
    'carb': 10,
    'type': ''
},
{
    'name': 'Nấm Rơm Kho',
    'number': 1,
    'name_word': 'Phần',
    'size': 100,
    'measure': 'gram',
    'calo': 154,
    'protein': 8,
    'fat': 11,
    'carb': 7,
    'type': ''
},
{
    'name': 'Cà Ri Chay',
    'number': 1,
    'name_word': 'Phần',
    'size': 160,
    'measure': 'gram',
    'calo': 278,
    'protein': 8,
    'fat': 11,
    'carb': 36,
    'type': ''
},
{
    'name': 'Snach',
    'number': 1,
    'name_word': 'Gói',
    'size': 24,
    'measure': 'gram',
    'calo': 124,
    'protein': 4,
    'fat': 4,
    'carb': 18,
    'type': ''
},
{
    'name': 'Bia',
    'number': 1,
    'name_word': 'Chai',
    'size': 330,
    'measure': 'ml',
    'calo': 36,
    'protein': 1.7,
    'fat': 0,
    'carb': 8.7,
    'type': 'Đồ uống'
},
{
    'name': 'Coca Cola',
    'number': 1,
    'name_word': 'Chai',
    'size': 330,
    'measure': 'ml',
    'calo': 138,
    'protein': 0,
    'fat': 0,
    'carb': 34,
    'type': 'Đồ uống'
},
{
    'name': 'Nước Cam',
    'number': 1,
    'name_word': 'Chai',
    'size': 330,
    'measure': 'ml',
    'calo': 76,
    'protein': 2.3,
    'fat': 0.7,
    'carb': 15,
    'type': 'Đồ uống'
},
{
    'name': 'Nước Dừa',
    'number': 1,
    'name_word': 'Chai',
    'size': 330,
    'measure': 'ml',
    'calo': 69,
    'protein': 1.3,
    'fat': 0,
    'carb': 16,
    'type': 'Đồ uống'
},
{
    'name': 'Trà sữa trân châu đường đen',
    'number': 1,
    'name_word': 'Cốc',
    'size': 500,
    'measure': 'ml',
    'calo': 250,
    'protein': 5,
    'fat': 10,
    'carb': 50,
    'type': 'Đồ uống'
},
{
    'name': 'Trà sữa matcha',
    'number': 1,
    'name_word': 'Ly',
    'size': 400,
    'measure': 'ml',
    'calo': 180,
    'protein': 3,
    'fat': 5,
    'carb': 35,
    'type': 'Đồ uống'
},
{
    'name': 'Cà phê đen đá',
    'number': 1,
    'name_word': 'Ly',
    'size': 350,
    'measure': 'ml',
    'calo': 5,
    'protein': 0.5,
    'fat': 0,
    'carb': 1,
    'type': 'Đồ uống'
},
{
    'name': 'Cà phê sữa',
    'number': 1,
    'name_word': 'Ly',
    'size': 350,
    'measure': 'ml',
    'calo': 80,
    'protein': 3,
    'fat': 3,
    'carb': 8,
    'type': 'Đồ uống'
},
{
    'name': 'Nước ép dưa hấu',
    'number': 1,
    'name_word': 'Ly',
    'size': 300,
    'measure': 'ml',
    'calo': 80,
    'protein': 1,
    'fat': 0,
    'carb': 20,
    'type': 'Đồ uống'
},
{
    'name': 'Sinh tố chuối',
    'number': 1,
    'name_word': 'Ly',
    'size': 400,
    'measure': 'ml',
    'calo': 200,
    'protein': 4,
    'fat': 5,
    'carb': 45,
    'type': 'Đồ uống'
},
{
    'name': 'Sinh tố bơ',
    'number': 1,
    'name_word': 'Ly',
    'size': 350,
    'measure': 'ml',
    'calo': 250,
    'protein': 3,
    'fat': 15,
    'carb': 30,
    'type': 'Đồ uống'
},

  // Thêm nhiều mục thức ăn ở đây
];
